services:
  - type: web
    name: wpcodingpress
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_APP_URL
        value: https://wpcodingpress.onrender.com
      - key: DATABASE_URL
        fromDatabase: wpcodingpress_db
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://wpcodingpress.onrender.com

databases:
  - name: wpcodingpress_db
    plan: free