export const EventTypes = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  EMAIL_VERIFICATION_REQUESTED: 'EMAIL_VERIFICATION_REQUESTED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  GUMROAD_PURCHASE_COMPLETED: 'GUMROAD_PURCHASE_COMPLETED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_UPGRADED: 'SUBSCRIPTION_UPGRADED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INVOICE_AVAILABLE: 'INVOICE_AVAILABLE',
  ONBOARDING_STARTED: 'ONBOARDING_STARTED',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  FEATURE_ACCESS_GRANTED: 'FEATURE_ACCESS_GRANTED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_REPLIED: 'SUPPORT_REPLIED',
  SUSPICIOUS_ACTIVITY_DETECTED: 'SUSPICIOUS_ACTIVITY_DETECTED',
} as const

export type EventType = (typeof EventTypes)[keyof typeof EventTypes]

export type EventPayload = Record<string, unknown>

export type EventHandler = (payload: EventPayload) => Promise<void>
